---
# tasks file for lvm_partition
- name: Creating new partition
  parted:
    device: '{{ device }}'
    number: '{{ part_number }}'
    flags: [ lvm ]
    state: present

- name: Create a new volume group
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ device }}{{ part_number }}"
    state: present

- name: Create the new logical volume
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: "{{ add_space }}{{ unit }}FREE"
    shrink: False

- name: Add a filesystem to the volume
  filesystem:
    fstype: "{{ filesystem }}"
    dev: "/dev/mapper/{{ vg_name }}-{{ lv_name }}"

- name: Create path for mount point
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: 0755

- name: Add mount to fstab and mount it
  mount:
    path: "{{ mount_point }}"
    src: "/dev/mapper/{{ vg_name }}-{{ lv_name }}"
    fstype: "{{ filesystem }}"
    state: mounted
